### PR TITLE
Add regex and config parsing unit tests + debian/rules fix + add skim to searches + skim unit test

### LINKED ISSUE #6: Use skim for searching
For better searching in general

### PR DESCRIPTION
**Pull request by iamnotmega**
This pull request will fix debian/rules to automatically compile Rustcast with the actual host triple instead of a hardcoded `--target x86_64-unknown-linux-gnu` flag. The PR will also add 5 new unit tests in `src/config/test.rs`:

- `test_regex_path_only` - makes sure that `include_patterns` can handle a simple file path (e.g `/home/ferris/rustcast`) without depth being specified (defaults to `1` in that case)
- `test_regex_with_explicit_depth` - same as `test_regex_path_only`, but this time the depth is explicitly specified, thus overriding the default value
- `test_regex_edge_cases` - makes sure that the compiler will not confuse colons in the file path with the colon preceding the depth (for example `this:is:a:pretty:long:path:10`)
- `test_regex_invalid_depth` - makes sure that the compiler will fall back to the default depth of `1` when an invalid depth (non-numerical, such as `:abc`) is supplied
- `test_parse_config` - makes sure the config file can be properly parsed by using the default config to create a temporary file on the user's disk to parse it

This PR will also make the search function use `skim` to make searching faster and less prone to typos leading to no results. This is in response to [#6](https://github.com/rustcast-cross/rustcast-cross/issues/6).

### CODE REVIEW

File: src/app/tile/update.rs [hunk 1]
```diff
@@ -306,85 +305,11 @@ pub fn handle_update(tile: &mut Tile, message: Message) -> Task<Message> {
             }
         }
 
-        Message::SwitchToPage(page) => {
```
Comment (Mnem42) [inline src/app/tile/update.rs:309]: Why did you remove `ClipboardHistory`?

File: src/config/test.rs [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    #[test]
+    fn test_regex_invalid_depth() {
+        let input = "/etc:abc";
+        let pattern: Pattern = input.parse().unwrap();
+
+        assert_eq!(pattern.max_depth, 1);
+    }
+
+    #[test]
+    fn test_parse_config() {
```
Comment (Mnem42) [inline src/config/test.rs:42]: Isn't this basically testing round trip parsing of `Config::default()`, so shouldn't it just serialize it and deserialize it without writing to disk?

File: src/commands.rs [hunk 3]
```diff
@@ -62,16 +87,17 @@ impl Function {
             }
 
             Function::OpenWebsite(url) => {
-                let open_url = if url.starts_with("http") {
-                    url.to_owned()
-                } else {
-                    format!("https://{url}")
-                };
+                if url.starts_with("http") {
+                    let open_url = if url.starts_with("http") {
```
Comment (Mnem42) [inline src/commands.rs]: Isn't it physically impossible for this if statement to return anything other than `url.to_owned()`?

File: Cargo.toml [hunk 4]
```diff
@@ -18,14 +18,6 @@ windows = { version = "0.58", features = [
...
 
 [target.'cfg(target_os = "macos")'.dependencies]
-objc2 = "0.6.3"
-objc2-app-kit = { version = "0.3.2", features = ["NSImage"] }
-objc2-application-services = { version = "0.3.2", default-features = false, features = [
-    "HIServices",
-    "Processes",
-] }
-objc2-core-foundation = "0.3.2"
-objc2-foundation = { version = "0.3.2", features = ["NSString"] }
```
Comment (Mnem42) [inline Cargo.toml:28]: I think this is why CI is failing on macos

File: src/app/tile/mod.rs [hunk 5]
```diff
@@ -152,13 +156,13 @@ impl Tile {
...
             #[cfg(target_os = "linux")]
-            Subscription::run(handle_socket),
+            Subscription::run(Self::handle_socket),
             keyboard,
-            Subscription::run(handle_recipient),
-            Subscription::run(handle_hot_reloading),
-            Subscription::run(handle_clipboard_history),
+            Subscription::run(Self::handle_recipient),
+            Subscription::run(Self::handle_hot_reloading),
+            Subscription::run(Self::handle_clipboard_history),
```
Comment (Mnem42) [inline src/app/tile/mod.rs:165]: Why did you make these associated fns?

(Not that it's a *bad* idea, I just want to know what your reasoning)

File: src/app/tile/mod.rs [hunk 6]
```diff
@@ -265,184 +280,183 @@ impl Tile {
     /// Restores the frontmost application.
     #[allow(deprecated, unused)]
     pub fn restore_frontmost(&mut self) {
+        #[cfg(target_os = "macos")]
+        use objc2_app_kit::NSApplicationActivationOptions;
```
Comment (Mnem42) [inline src/app/tile/mod.rs:284]: What's your reasoning for moving the use statement?

File: src/app/tile/test.rs [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+
+        let matcher = SkimMatcherV2::default();
+        let query = "ffox";
+
+        let score_firefox = matcher.fuzzy_match("firefox", query).unwrap_or(0);
+        let score_fileman = matcher.fuzzy_match("files", query).unwrap_or(0);
+
+        assert!(score_firefox > score_fileman);
+    }
+}
```
Comment (Mnem42) [inline src/app/tile/test.rs:18]: Isn't this just testing if the library works, which isn't really our responsibility?

File: src/main.rs [hunk 8]
```diff
@@ -28,7 +28,7 @@ use crate::hotkey::init_hotkey_manager;
 #[cfg(target_os = "linux")]
 use crate::hotkey::init_socket;
 
-fn parse_cfg_file(path: impl AsRef<Path>) -> anyhow::Result<Config> {
+pub fn parse_cfg_file(path: impl AsRef<Path>) -> anyhow::Result<Config> {
```
Comment (Mnem42) [inline src/main.rs:31]: I think you forgot to remove the duplicate definition of this (but the other usage only exists because of me being dumb, so yeah)

File: src/app/tile/mod.rs [hunk 9]
```diff
@@ -265,184 +280,183 @@ impl Tile {
...
                 std::env::var("HOME").unwrap_or_default() + "/.config/rustcast/config.toml",
             )
             .unwrap_or_default();
 
-            let current_total_files: usize = paths
+            let paths = default_app_paths();
+            let mut total_files: usize = paths
                 .par_iter()
-                .map(|dir| count_dirs_in_dir(&dir.to_owned().into()))
+                .map(|dir| Self::count_dirs_in_dir(&dir.to_owned().into()))
```
Comment (Mnem42) [inline src/app/tile/mod.rs:312]: Is this really that associated with `Tile`? (well, but also, I have no idea why this wasn't originally made in utils or smth)

File: src/commands.rs [hunk 10]
```diff
@@ -91,12 +117,11 @@ impl Function {
             #[cfg(target_os = "macos")]
```
Comment (Mnem42) [inline src/commands.rs]: Can't this now be `#[cfg(any(target_os="macos", target_os="linux"))]`?

**Review by Mnem42 — CHANGES_REQUESTED** [review]
Seems mostly good to me

File: src/commands.rs (hunk 3 above)
Comment (Mnem42) [reply src/commands.rs]: Actually, doesn't this change the behaviour?

File: src/app/tile/mod.rs [hunk 11]
```diff
@@ -220,19 +224,30 @@ impl Tile {
...
     pub fn handle_search_query_changed(&mut self) {
         let query = self.query_lc.clone();
+
         let options = if self.page == Page::Main {
             &self.options
         } else if self.page == Page::EmojiSearch {
             &self.emoji_apps
         } else {
-            &AppIndex::from_apps(vec![])
+            return;
```
Comment (Mnem42) [inline src/app/tile/mod.rs:233]: I'd rewrite it as a match statement

Comment (Mnem42) [reply src/app/tile/mod.rs:233]: mb, this isn't actually from your code

File: src/app/tile/test.rs (hunk 7 above)
Comment (iamnotmega) [reply src/app/tile/test.rs:18]: yeah but i think its a good idea to make sure it even WORKS in the first place

File: src/app/tile/update.rs (hunk 1 above)
Comment (iamnotmega) [reply src/app/tile/update.rs:309]: its now added back

File: src/config/test.rs (hunk 2 above)
Comment (iamnotmega) [reply src/config/test.rs:42]: i revised it now

File: src/commands.rs (hunk 3 above)
Comment (iamnotmega) [reply src/commands.rs]: i removed the HTTP check entirely and just made it accept any URL

File: src/main.rs (hunk 8 above)
Comment (iamnotmega) [reply src/main.rs:31]: i removed the duplicate definition, dw

File: src/app/tile/mod.rs (hunk 5 above)
Comment (iamnotmega) [reply src/app/tile/mod.rs:165]: im pretty sure these functions got moved into Tile and i didnt want to keep calling Tile all the time

File: src/app/tile/mod.rs (hunk 9 above)
Comment (iamnotmega) [reply src/app/tile/mod.rs:312]: i personally have no idea

**Comment by iamnotmega** [comment]
i have now addressed your suggestions @Mnem42 please review it again

File: src/app/tile/test.rs (hunk 7 above)
Comment (Mnem42) [reply src/app/tile/test.rs:18]: But why, since the library already has unit tests to check for the ranking working

**Comment by Mnem42** [comment]
LGTM
